// <auto-generated />
using SampleAspNetWithEfCore.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace SampleAspNetWithEfCore.Migrations
{
    [DbContext(typeof(PeopleDbContext))]
    [Migration("20181120214813_Initialize")]
    partial class Initialize
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SampleAspNetWithEfCore.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("People");
                });

            modelBuilder.Entity("SampleAspNetWithEfCore.Team", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Teams");
                });

            modelBuilder.Entity("SampleAspNetWithEfCore.TeamUser", b =>
                {
                    b.Property<int>("TeamId");

                    b.Property<string>("UserName");

                    b.HasKey("TeamId", "UserName");

                    b.ToTable("TeamUsers");
                });

            modelBuilder.Entity("SampleAspNetWithEfCore.Person", b =>
                {
                    b.OwnsOne("SampleAspNetWithEfCore.Pet", "Pet", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.Property<int>("Animal");

                            b1.Property<string>("Name");

                            b1.ToTable("People");

                            b1.HasOne("SampleAspNetWithEfCore.Person")
                                .WithOne("Pet")
                                .HasForeignKey("SampleAspNetWithEfCore.Pet", "Id")
                                .OnDelete(DeleteBehavior.Cascade);
                        });
                });

            modelBuilder.Entity("SampleAspNetWithEfCore.TeamUser", b =>
                {
                    b.HasOne("SampleAspNetWithEfCore.Team")
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
